strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 1
image:
  image_registry: acrargopogwizdow.azurecr.io
  image_repository: r1.nginx
  environment: dev-
  version_major: '1'
  version_minor: '17'
  version_patch: b700f9c
  pullPolicy: Always
serviceAccount:
  name: sa-dev-r1-nginx
service:
  type: ClusterIP
  port: 80
  targetPort: 80
